// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/system/dao/internal"
)

// internalCountryDao is internal type for wrapping internal DAO implements.
type internalCountryDao = *internal.CountryDao

// countryDao is the data access object for table ue_system_country.
// You can define custom methods on it to extend its functionality as you wish.
type countryDao struct {
	internalCountryDao
}

var (
	// Country is globally public accessible object for table ue_system_country operations.
	Country = countryDao{
		internal.NewCountryDao(),
	}
)

// Fill with you ideas below.
