// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/system/dao/internal"
)

// internalCurrencyDao is internal type for wrapping internal DAO implements.
type internalCurrencyDao = *internal.CurrencyDao

// currencyDao is the data access object for table ue_system_currency.
// You can define custom methods on it to extend its functionality as you wish.
type currencyDao struct {
	internalCurrencyDao
}

var (
	// Currency is globally public accessible object for table ue_system_currency operations.
	Currency = currencyDao{
		internal.NewCurrencyDao(),
	}
)

// Fill with you ideas below.
