// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/system/dao/internal"
)

// internalLanguageDao is internal type for wrapping internal DAO implements.
type internalLanguageDao = *internal.LanguageDao

// languageDao is the data access object for table ue_system_language.
// You can define custom methods on it to extend its functionality as you wish.
type languageDao struct {
	internalLanguageDao
}

var (
	// Language is globally public accessible object for table ue_system_language operations.
	Language = languageDao{
		internal.NewLanguageDao(),
	}
)

// Fill with you ideas below.
