// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/system/dao/internal"
)

// internalSystemEventDao is internal type for wrapping internal DAO implements.
type internalSystemEventDao = *internal.SystemEventDao

// systemEventDao is the data access object for table ue_system_event.
// You can define custom methods on it to extend its functionality as you wish.
type systemEventDao struct {
	internalSystemEventDao
}

var (
	// SystemEvent is globally public accessible object for table ue_system_event operations.
	SystemEvent = systemEventDao{
		internal.NewSystemEventDao(),
	}
)

// Fill with you ideas below.
