# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "hotgo"                          # 编译后的可执行文件名称
#    arch: "all"                           #不填默认当前系统架构，可选：386,amd64,arm,all
#    system: "all"                         #不填默认当前系统平台，可选：linux,darwin,windows,all
    mod: "none"
    cgo: 0
    packSrc: "resource"                    # 将resource目录打包进可执行文件，静态资源无需单独部署
    packDst: "internal/packed/packed.go"   # 打包后生成的Go文件路径，一般使用相对路径指定到本项目目录中
    version: ""
    output: "./temp/hotgo"                 # 可执行文件生成路径
    extra: ""


  docker:
    build: "-a amd64 -s linux -p temp -ew"   # 构建参数
    tagPrefixes:                             # 该docker的标记前缀，用于docker推送，请替换成你自己的
      - ccr.ccs.tencentyun.com/bufanyun


  gen:
    dao:
      - link: "mysql:root:1q2w3e4r@tcp(36.7.120.174:13306)/wh?loc=Local&parseTime=true"
        group: "wh"
        table: "ue_fang"
        removePrefix: "ue_"
        descriptionTag: true
        noModelComment: true
        jsonCase: "Snake"
        gJsonSupport: true
        clear: false
        stdTime: false
        path: ./addons/fang


#    service: # 生成业务配置
#      srcFolder: "internal/logic"
#      dstFolder: "internal/service"
#      dstFileNameCase: "CamelLower"
#      clear: true