// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/cloudflare/dao/internal"
)

// internalAccountDao is internal type for wrapping internal DAO implements.
type internalAccountDao = *internal.AccountDao

// accountDao is the data access object for table ue_cf_account.
// You can define custom methods on it to extend its functionality as you wish.
type accountDao struct {
	internalAccountDao
}

var (
	// Account is globally public accessible object for table ue_cf_account operations.
	Account = accountDao{
		internal.NewAccountDao(),
	}
)

// Fill with you ideas below.
