// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/cloudflare/dao/internal"
)

// internalSslDao is internal type for wrapping internal DAO implements.
type internalSslDao = *internal.SslDao

// sslDao is the data access object for table ue_cf_domain_ssl.
// You can define custom methods on it to extend its functionality as you wish.
type sslDao struct {
	internalSslDao
}

var (
	// Ssl is globally public accessible object for table ue_cf_domain_ssl operations.
	Ssl = sslDao{
		internal.NewSslDao(),
	}
)

// Fill with you ideas below.
