// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/fang/dao/internal"
)

// internalFangDao is internal type for wrapping internal DAO implements.
type internalFangDao = *internal.FangDao

// fangDao is the data access object for table ue_fang.
// You can define custom methods on it to extend its functionality as you wish.
type fangDao struct {
	internalFangDao
}

var (
	// Fang is globally public accessible object for table ue_fang operations.
	Fang = fangDao{
		internal.NewFangDao(),
	}
)

// Fill with you ideas below.
