// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/fang/dao/internal"
)

// internalVillageDao is internal type for wrapping internal DAO implements.
type internalVillageDao = *internal.VillageDao

// villageDao is the data access object for table ue_village.
// You can define custom methods on it to extend its functionality as you wish.
type villageDao struct {
	internalVillageDao
}

var (
	// Village is globally public accessible object for table ue_village operations.
	Village = villageDao{
		internal.NewVillageDao(),
	}
)

// Fill with you ideas below.
