// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/order/dao/internal"
)

// internalOrderTimeCompleteDao is internal type for wrapping internal DAO implements.
type internalOrderTimeCompleteDao = *internal.OrderTimeCompleteDao

// orderTimeCompleteDao is the data access object for table ue_order_time_complete.
// You can define custom methods on it to extend its functionality as you wish.
type orderTimeCompleteDao struct {
	internalOrderTimeCompleteDao
}

var (
	// OrderTimeComplete is globally public accessible object for table ue_order_time_complete operations.
	OrderTimeComplete = orderTimeCompleteDao{
		internal.NewOrderTimeCompleteDao(),
	}
)

// Fill with you ideas below.
