// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/user/dao/internal"
)

// internalAffiliateDao is internal type for wrapping internal DAO implements.
type internalAffiliateDao = *internal.AffiliateDao

// affiliateDao is the data access object for table ue_user_affiliate.
// You can define custom methods on it to extend its functionality as you wish.
type affiliateDao struct {
	internalAffiliateDao
}

var (
	// Affiliate is globally public accessible object for table ue_user_affiliate operations.
	Affiliate = affiliateDao{
		internal.NewAffiliateDao(),
	}
)

// Fill with you ideas below.
