// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/user/dao/internal"
)

// internalSocialDao is internal type for wrapping internal DAO implements.
type internalSocialDao = *internal.SocialDao

// socialDao is the data access object for table ue_user_social.
// You can define custom methods on it to extend its functionality as you wish.
type socialDao struct {
	internalSocialDao
}

var (
	// Social is globally public accessible object for table ue_user_social operations.
	Social = socialDao{
		internal.NewSocialDao(),
	}
)

// Fill with you ideas below.
