// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/bee/dao/internal"
)

// internalSystemSiteDao is internal type for wrapping internal DAO implements.
type internalSystemSiteDao = *internal.SystemSiteDao

// systemSiteDao is the data access object for table ue_system_site.
// You can define custom methods on it to extend its functionality as you wish.
type systemSiteDao struct {
	internalSystemSiteDao
}

var (
	// SystemSite is globally public accessible object for table ue_system_site operations.
	SystemSite = systemSiteDao{
		internal.NewSystemSiteDao(),
	}
)

// Fill with you ideas below.
