// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/bee/dao/internal"
)

// internalUserLoginInfoDao is internal type for wrapping internal DAO implements.
type internalUserLoginInfoDao = *internal.UserLoginInfoDao

// userLoginInfoDao is the data access object for table ue_user_login_info.
// You can define custom methods on it to extend its functionality as you wish.
type userLoginInfoDao struct {
	internalUserLoginInfoDao
}

var (
	// UserLoginInfo is globally public accessible object for table ue_user_login_info operations.
	UserLoginInfo = userLoginInfoDao{
		internal.NewUserLoginInfoDao(),
	}
)

// Fill with you ideas below.
