// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/bee/dao/internal"
)

// internalUserAffiliateDao is internal type for wrapping internal DAO implements.
type internalUserAffiliateDao = *internal.UserAffiliateDao

// userAffiliateDao is the data access object for table ue_user_affiliate.
// You can define custom methods on it to extend its functionality as you wish.
type userAffiliateDao struct {
	internalUserAffiliateDao
}

var (
	// UserAffiliate is globally public accessible object for table ue_user_affiliate operations.
	UserAffiliate = userAffiliateDao{
		internal.NewUserAffiliateDao(),
	}
)

// Fill with you ideas below.
