// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/bee/dao/internal"
)

// internalUserSocialDao is internal type for wrapping internal DAO implements.
type internalUserSocialDao = *internal.UserSocialDao

// userSocialDao is the data access object for table ue_user_social.
// You can define custom methods on it to extend its functionality as you wish.
type userSocialDao struct {
	internalUserSocialDao
}

var (
	// UserSocial is globally public accessible object for table ue_user_social operations.
	UserSocial = userSocialDao{
		internal.NewUserSocialDao(),
	}
)

// Fill with you ideas below.
