// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/game/dao/internal"
)

// internalGameDao is internal type for wrapping internal DAO implements.
type internalGameDao = *internal.GameDao

// gameDao is the data access object for table ue_game.
// You can define custom methods on it to extend its functionality as you wish.
type gameDao struct {
	internalGameDao
}

var (
	// Game is globally public accessible object for table ue_game operations.
	Game = gameDao{
		internal.NewGameDao(),
	}
)

// Fill with you ideas below.
